name: "exploreshare"
description: "expand the directory on the cloud disk, such as aliyundrive."
author: "sucody"

inputs:
  gh-token:
    description: 'The GitHub token for authentication.'
    required: true
  label:
    description: 'The label to be applied to the pull request.'
    required: true

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: 'activity'
  color: 'green'