name: deploy

on:
  workflow_dispatch:

jobs:
  deploy-explorer:
    name: deploy explorer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy --name ${{ secrets.CF_WORKER_NAME }} --var YUNZIYUAN_HOST:${{ secrets.YUNZIYUAN_HOST }} YUNZIYUAN_EXPLORER:${{ secrets.YUNZIYUAN_EXPLORER }} YUNZIYUAN_TOKEN:${{ secrets.YUNZIYUAN_TOKEN }}
